#!/usr/bin/env bash
set -euo pipefail

export MIND2WEB_STATE_PACKET_ENABLE="${MIND2WEB_STATE_PACKET_ENABLE:-1}"
export MIND2WEB_STATE_PACKET_DEBUG="${MIND2WEB_STATE_PACKET_DEBUG:-1}"
export MIND2WEB_STATE_PACKET_CACHE_DIR="${MIND2WEB_STATE_PACKET_CACHE_DIR:-/tmp/mind2web_state_packet_cache}"
export MIND2WEB_STATE_PACKET_PATCH_SIZE="${MIND2WEB_STATE_PACKET_PATCH_SIZE:-16}"
export MIND2WEB_STATE_PACKET_MERGE_SIZE="${MIND2WEB_STATE_PACKET_MERGE_SIZE:-2}"
export MIND2WEB_STATE_PACKET_THUMB_LONG_EDGE="${MIND2WEB_STATE_PACKET_THUMB_LONG_EDGE:-192}"
export MIND2WEB_STATE_PACKET_ROI_LONG_EDGE="${MIND2WEB_STATE_PACKET_ROI_LONG_EDGE:-224}"
export MIND2WEB_STATE_PACKET_ROI_SHORT_SIDE_RATIO="${MIND2WEB_STATE_PACKET_ROI_SHORT_SIDE_RATIO:-0.22}"
export MIND2WEB_STATE_PACKET_ROI_MIN_SIDE_PX="${MIND2WEB_STATE_PACKET_ROI_MIN_SIDE_PX:-160}"
export QWEN3VL_ENABLE_STRUCTURED_FAST_DECODE="${QWEN3VL_ENABLE_STRUCTURED_FAST_DECODE:-0}"

TAG="${TAG:-hist2_state_packet}"
PYTHON_BIN="${PYTHON_BIN:-/home/ytshen/anaconda3/envs/qwen3_5/bin/python}"
TORCHRUN_BIN="${TORCHRUN_BIN:-/home/ytshen/anaconda3/envs/qwen3_5/bin/torchrun}"

bash RUN_BASH/run_qwen3vl_mind2web_4B.sh

